'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {PreferenceControls,useLocale} from '../preferences';
import AccountAvatar from '../account-avatar';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Kind='items'|'bookings'|'members'|'audit';
type Row={id:string;title?:string;series?:string;ownerName?:string;size?:string;city?:string;price?:number;active?:number;moderationReason?:string;created?:number;renterName?:string;start?:string;end?:string;status?:string;total?:number;name?:string;email?:string;listings?:number;rentals?:number;actorName?:string;action?:string;target?:string;reason?:string};
type Summary={items:number;active:number;members:number;pending:number;accepted:number};
type Selection={row:Row;action:'moderate'|'cancel';active?:boolean};
export default function AdminPanel({name,picture}:{name:string;picture?:string|null}){
 const {language}=useLocale();const L=(zh:string,en:string)=>language==='en'?en:zh;
 const [kind,setKind]=useState<Kind>('items'),[search,setSearch]=useState(''),[q,setQ]=useState(''),[page,setPage]=useState(1),[reload,setReload]=useState(0);
 const [rows,setRows]=useState<Row[]>([]),[summary,setSummary]=useState<Summary|null>(null),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [selection,setSelection]=useState<Selection|null>(null),[reason,setReason]=useState(''),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch(`/api/admin?kind=${kind}&page=${page}&q=${encodeURIComponent(q)}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json() as {error?:string;rows:Row[];summary:Summary;hasMore:boolean};if(!r.ok)throw new Error(d.error);if(!controller.signal.aborted){setRows(d.rows);setSummary(d.summary);setMore(d.hasMore)}}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[kind,page,q,reload]);
 function choose(value:Selection){setSelection(value);setReason('');setSaveError('');setMessage('')}
 async function save(e:FormEvent){e.preventDefault();if(!selection)return;setSaving(true);setSaveError('');const {row,action,active}=selection;
  try{const body=action==='moderate'?{action,id:row.id,active,expectedActive:row.active,reason}:{action,id:row.id,expectedStatus:row.status,reason};const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setSelection(null);setMessage(L('操作已儲存並記錄。','Saved and recorded in the audit log.'));setReload(v=>v+1)}catch(e){setSaveError(e instanceof Error?e.message:L('無法儲存','Unable to save'))}finally{setSaving(false)}
 }
 const status=(s?:string)=>({pending:L('待確認','Pending'),accepted:L('已確認','Accepted'),declined:L('已婉拒','Declined'),cancelled:L('已取消','Cancelled')}[s||'']||s);
 const date=(n?:number)=>n?new Intl.DateTimeFormat(language==='en'?'en-US':'zh-TW',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Taipei'}).format(n):'—';
 const money=(n?:number)=>`NT$ ${(n??0).toLocaleString()}`;
 const tabs:[Kind,string][]=[['items',L('服裝管理','Listings')],['bookings',L('租借管理','Rentals')],['members',L('會員查詢','Members')],['audit',L('操作紀錄','Audit log')]];
 return <div className="admin-shell"><header className="admin-header"><a className="brand" href="/"><img src="/coz-logo-transparent.png" width="40" height="40" alt=""/><span>COZ COS CLOSET<small>{L('管理後台','Administration')}</small></span></a><div className="admin-account"><PreferenceControls/><AccountAvatar name={name} picture={picture}/><a href="/explore">{L('探索衣櫃','Explore')}</a><form action="/api/auth/logout" method="post"><button>{L('登出','Sign out')}</button></form></div></header>
 <main className="admin-main"><div className="admin-heading"><div><p className="admin-eyebrow">WARDROBE OPERATIONS</p><h1>{L('管理後台','Administration')}</h1><p>{L('歡迎回來，','Welcome back, ')}{name}</p></div><button onClick={()=>setReload(v=>v+1)} disabled={loading}>{L('重新整理','Refresh')}</button></div>
 <section className="admin-stats" aria-label={L('網站統計','Site statistics')}>{([['items',L('服裝總數','Total listings')],['active',L('上架中','Active listings')],['members',L('會員','Members')],['pending',L('待確認租借','Pending rentals')],['accepted',L('已確認租借','Accepted rentals')]] as [keyof Summary,string][]).map(([key,label])=><div key={key}><span>{label}</span><strong>{summary?summary[key].toLocaleString():'—'}</strong></div>)}</section>
 <nav className="admin-tabs" aria-label={L('管理功能','Management sections')}>{tabs.map(([value,label])=><button key={value} aria-pressed={kind===value} onClick={()=>{setKind(value);setPage(1);setQ('');setSearch('');setMessage('')}}>{label}</button>)}</nav>
 <section className="admin-section"><form className="admin-search" onSubmit={e=>{e.preventDefault();setQ(search.trim());setPage(1)}}><label htmlFor="admin-search">{L('搜尋','Search')}</label><input id="admin-search" value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} placeholder={kind==='items'?L('服裝或出租者名稱','Listing or owner name'):kind==='bookings'?L('服裝或租借者名稱','Listing or renter name'):kind==='members'?L('姓名或 Email','Name or email'):L('目標編號或原因','Target ID or reason')}/><button>{L('查詢','Search')}</button></form>
 {message&&<p className="admin-success" role="status">{message}</p>}{error?<p className="admin-error" role="alert">{error}</p>:loading?<p className="admin-empty" role="status">{L('載入中…','Loading…')}</p>:rows.length===0?<p className="admin-empty">{L('沒有符合條件的資料。','No matching records.')}</p>:<div className="admin-table-wrap"><table><caption className="visually-hidden">{tabs.find(t=>t[0]===kind)?.[1]}</caption><thead><tr>{(kind==='items'?[L('服裝','Listing'),L('出租者／尺寸','Owner / size'),L('每日租金','Daily price'),L('狀態','Status'),L('管理','Actions')]:kind==='bookings'?[L('服裝／出租者','Listing / owner'),L('租借者','Renter'),L('租期／租金','Dates / total'),L('狀態','Status'),L('管理','Actions')]:kind==='members'?[L('會員','Member'),'Email',L('服裝／租借數','Listings / rentals'),L('加入時間','Joined')]:[L('操作時間','Time'),L('管理員／操作','Admin / action'),L('目標編號','Target ID'),L('原因','Reason')]).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}>
 {kind==='items'?<><td><strong>{row.title}</strong><small>{row.series} · {row.city}</small><small>{row.id}</small></td><td>{row.ownerName}<small>{row.size}</small></td><td>{money(row.price)}</td><td><span className={`admin-badge ${row.active?'positive':''}`}>{row.active?L('上架中','Active'):row.moderationReason?L('管理下架','Moderated'):L('已下架','Inactive')}</span>{row.moderationReason&&<small>{row.moderationReason}</small>}</td><td><button onClick={()=>choose({row,action:'moderate',active:!row.active})}>{row.active?L('管理下架','Hide listing'):L('恢復上架','Restore listing')}</button></td></>:kind==='bookings'?<><td><strong>{row.title}</strong><small>{row.ownerName}</small><small>{row.id}</small></td><td>{row.renterName}</td><td>{row.start} → {row.end}<small>{money(row.total)}</small></td><td><span className={`admin-badge ${row.status==='accepted'?'positive':''}`}>{status(row.status)}</span></td><td>{['pending','accepted'].includes(row.status||'')?<button onClick={()=>choose({row,action:'cancel'})}>{L('取消租借','Cancel rental')}</button>:'—'}</td></>:kind==='members'?<><td><strong>{row.name}</strong><small>{row.id}</small></td><td>{row.email}</td><td>{row.listings} / {row.rentals}</td><td>{date(row.created)}</td></>:<><td>{date(row.created)}</td><td>{row.actorName}<small>{row.action==='hide_item'?L('管理下架','Hide listing'):row.action==='restore_item'?L('恢復上架','Restore listing'):L('取消租借','Cancel rental')}</small></td><td className="admin-id">{row.target}</td><td>{row.reason}</td></>}
 </tr>)}</tbody></table></div>}
 <div className="admin-pagination"><button disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}>{L('上一頁','Previous')}</button><span>{L('第','Page ')} {page} {L('頁','')}</span><button disabled={!more||loading||!!error} onClick={()=>setPage(p=>p+1)}>{L('下一頁','Next')}</button></div></section>
 <p className="admin-footnote">{L('管理操作會留下紀錄。取消租借只更新平台狀態，款項與交付仍需聯絡雙方處理。','Management actions are logged. Cancelling a rental updates its platform status; contact both parties about payments and delivery.')}</p></main>
 <Dialog open={!!selection} onOpenChange={open=>{if(!open&&!saving)setSelection(null)}}><DialogContent showCloseButton={!saving} className="admin-dialog"><DialogTitle>{selection?.action==='cancel'?L('確認取消租借','Confirm rental cancellation'):selection?.active?L('確認恢復上架','Confirm listing restoration'):L('確認管理下架','Confirm listing moderation')}</DialogTitle><DialogDescription>{selection?.row.title}{selection?.action==='cancel'&&` · ${selection.row.start} → ${selection.row.end}`}</DialogDescription><form onSubmit={save}><p>{selection?.action==='cancel'?L('請先與雙方確認。已確認租借取消後，該租期將重新開放；這不會自動退款。','Confirm with both parties. Cancelling an accepted rental frees its dates and does not issue a refund.'):selection?.active?L('恢復後所有人都可以提出租借申請。','Restoring this listing makes it available for rental requests.'):L('下架後停止新申請，出租者無法自行恢復。既有租借不會自動取消。','Hiding blocks new requests and owner restoration. Existing rentals remain unchanged.')}</p><label htmlFor="admin-reason">{L('操作原因（必填）','Reason (required)')}</label><textarea id="admin-reason" required minLength={2} maxLength={300} rows={4} value={reason} onChange={e=>setReason(e.target.value)} disabled={saving}/><small>{reason.length}/300</small>{saveError&&<p className="admin-error" role="alert">{saveError}</p>}<div className="admin-dialog-actions"><button type="button" disabled={saving} onClick={()=>setSelection(null)}>{L('返回','Back')}</button><button className="admin-confirm" disabled={saving||reason.trim().length<2}>{saving?L('儲存中…','Saving…'):L('確認操作','Confirm')}</button></div></form></DialogContent></Dialog></div>
}
