'use client';
import {useLocale,PreferenceControls} from './preferences';
import {ArrowUpRight,ArrowRight,Sparkles,Shirt,Scan,PackageCheck} from 'lucide-react';
import './landing.css';
import CostumeShowcase from './costume-showcase';
export default function Home(){const {t}=useLocale();return <div className="portal-page">
<header className="portal-nav"><a href="/" className="portal-brand"><img src="/coz-logo-transparent.png" width="42" height="42" alt=""/><span>COZ COS CLOSET<small>{t("你的次元共用衣櫃")}</small></span></a><nav aria-label={t("首頁導覽")}><a className="about-link" href="#how">{t("租借怎麼玩")}</a><PreferenceControls/><a className="portal-login" href="/login">{t("登入")}</a></nav></header>
<main><section className="portal-hero"><div className="hero-copy"><div className="hero-edition">REAL CLOTHES. ANOTHER YOU.</div><h1>{t("下一個角色，")}<br/><span>{t("換你登場。")}</span><Sparkles className="title-spark" aria-hidden="true"/></h1><p>{t("想成為的角色，不必只存在螢幕裡。")}<br/>{t("租一套心動的 Cos 服，")}<br className="hero-mobile-break"/>{t("把下一場故事穿在身上。")}</p></div><CostumeShowcase/><div className="hero-actions"><a className="portal-cta" href="/explore">{t("開始租借")}<ArrowUpRight size={23}/></a><a className="portal-secondary" href="/explore?view=upload">{t("分享我的衣櫃")}<ArrowRight size={17}/></a></div><div className="hero-footnote"><span>{t("衣服共享 · 熱愛不設限")}</span></div></section>
<div className="scene-strip" aria-hidden="true"><div className="scene-track">{[0,1].map(copy=><div className="scene-group" key={copy}>{['COSPLAY','ANIME','GAME','ANOTHER YOU','COSPLAY','ANIME','GAME','ANOTHER YOU'].map((word,index)=><span className="scene-word" key={index}><span>{word}</span><span>✦</span></span>)}</div>)}</div></div>
<section className="portal-about" aria-labelledby="about-coz"><div className="portal-kicker">COZ COS CLOSET</div><h2 id="about-coz">{t("Cosplay 服裝租借，讓衣櫃裡的熱愛再次登場。")}</h2><p>{t("COZ COS CLOSET 是以 Cosplay 服裝租借與分享為主的共用衣櫃平台。無論是動漫、遊戲角色或原創服裝，都能查看照片、服裝品牌與尺寸資訊，依地區和租期尋找合適的裝備；出租者也能上架自己的 Cos 服裝，讓更多同好延續角色的故事。")}</p></section><section id="how" className="portal-how"><div className="section-intro"><div className="portal-kicker">YOUR NEXT QUEST</div><h2>{t("出角準備，")}<br/>{t("從這裡開始。")}</h2><p>{t("從心動的服裝，到真實的相遇。")}</p></div><div className="quest-grid">{[{icon:Shirt,n:'01',title:'找到命定裝備',text:'探索角色與服裝，查看多張照片、品牌和尺寸，找到適合自己的那一套。'},{icon:Scan,n:'02',title:'和衣主確認任務',text:'選擇租期提出申請，衣主確認後，再一起約定付款與交付方式。'},{icon:PackageCheck,n:'03',title:'登場，延續故事',text:'穿上熱愛的角色，依約歸還服裝，讓這份熱愛迎接下一位同好。'}].map(({icon:Icon,n,title,text})=><article className="quest-card" key={n}><div><Icon size={25}/><span>QUEST / {n}</span></div><h3>{t(title)}</h3><p>{t(text)}</p></article>)}</div></section>
<section className="portal-finale"><span>{t("衣櫃裡的寶藏，值得更多舞台。")}</span><h2>{t("你的下一場，")}<br className="hero-mobile-break"/>{t("現在開場。")}</h2><small>{t("目前付款與交付由雙方約定，平台尚未提供線上收款。")}</small></section></main><footer className="portal-footer"><a href="/" className="portal-brand"><img src="/coz-logo-transparent.png" width="28" height="28" alt=""/>COZ COS CLOSET</a><span>FOR EVERY VERSION OF YOU. ✦</span></footer></div>}
