'use client';
import {useLocale} from './preferences';

import {useEffect,useRef,useState} from 'react';
import {Camera,ChevronLeft,ChevronRight,ExternalLink,X} from 'lucide-react';
import {toast} from 'sonner';
import type {Item,Booking} from '@/lib/catalog';
import type {ListingDetails} from '@/lib/listing-details';

export function UploadPhotos({files,onChange}:{files:File[];onChange:(files:File[])=>void}){const {t}=useLocale();
 const input=useRef<HTMLInputElement>(null);const [urls,setUrls]=useState<string[]>([]);
 useEffect(()=>{const next=files.map(f=>URL.createObjectURL(f));setUrls(next);return()=>next.forEach(url=>URL.revokeObjectURL(url))},[files]);
 return <section className="upload-photo-panel"><button type="button" className="upload-drop" onClick={()=>input.current?.click()}><Camera size={38}/><strong>{files.length?t("繼續新增照片"):t("上傳服裝照片")}</strong><span>{t("正面、背面、配件與衣況細節")}</span><small>{t("最多 6 張・每張 5 MB・合計 20 MB")}</small></button><input ref={input} className="visually-hidden" type="file" aria-label={t("新增服裝照片")} accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{const next=[...files,...Array.from(e.target.files??[])];e.target.value='';if(next.length>6)return void toast.error(t("每套服裝最多 6 張照片"));if(next.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size===0||f.size>5*1024*1024))return void toast.error(t("每張照片須為 5 MB 以內的 JPG、PNG 或 WebP"));if(next.reduce((sum,f)=>sum+f.size,0)>20*1024*1024)return void toast.error(t("照片合計請勿超過 20 MB"));onChange(next)}}/>
 <div className="upload-thumbnails">{urls.map((url,index)=><div className="upload-thumb" key={url}><img src={url} alt={`${t("待上架照片")} ${index+1}`}/><button type="button" className="remove-photo" aria-label={`${t("移除照片")} ${index+1}`} onClick={()=>onChange(files.filter((_,i)=>i!==index))}><X size={16}/></button><button type="button" className="cover-choice" disabled={index===0} onClick={()=>onChange([files[index],...files.filter((_,i)=>i!==index)])}>{index===0?t("封面"):t("設為封面")}</button></div>)}</div><p>{t("已選")}{files.length} {t("/ 6 張。請使用自己的實拍照；第一張會顯示在衣櫃列表。")}</p></section>
}
export function ListingFields(){const {t}=useLocale();return <>
 <label>{t("服裝品牌（選填）")}<input name="brand" maxLength={80} placeholder={t("例如：三分妄想／自製／不詳")}/></label>
 <fieldset className="listing-fieldset"><legend>{t("出租者社群（選填）")}</legend><p>{t("填寫自己的公開個人頁，讓租借者認識你，也方便聯絡。連結會公開顯示。")}</p><label>Facebook<input name="facebook" type="url" maxLength={300} placeholder={t("https://www.facebook.com/你的個人頁")}/></label><label>Instagram<input name="instagram" type="url" maxLength={300} placeholder={t("https://www.instagram.com/你的帳號/")}/></label></fieldset>
 <fieldset className="listing-fieldset"><legend>{t("試穿者身形（全部選填）")}</legend><p>{t("填寫穿過這套服裝的人的數據，會公開展示。這不是衣服平量尺寸，不想公開的項目可留白。")}</p><div className="measurement-grid">{[['height','身高（cm）',80,250],['weight','體重（kg）',20,250],['bust','胸圍（cm）',30,200],['waist','腰圍（cm）',30,200],['hips','臀圍（cm）',30,200]].map(([name,label,min,max])=><label key={name} htmlFor={'fit-'+name}>{t(String(label))}<input id={'fit-'+name} name={String(name)} type="number" min={min} max={max} step="0.1" placeholder={t("選填")}/></label>)}</div><label>{t("試穿感受")}<input name="fitNote" maxLength={300} placeholder={t("例如：腰部偏緊、背後綁帶可調整；也可在衣況欄補充平量尺寸")}/></label></fieldset>
 </>}
export function SocialLinks({details}:{details?:Partial<ListingDetails>}){const {t}=useLocale();if(!details?.facebook&&!details?.instagram)return null;return <div className="social-links">{details.facebook&&<a href={details.facebook} target="_blank" rel="noopener noreferrer">Facebook <ExternalLink size={14}/></a>}{details.instagram&&<a href={details.instagram} target="_blank" rel="noopener noreferrer">Instagram <ExternalLink size={14}/></a>}<small>{t("出租者自行提供，平台尚未驗證帳號歸屬。")}</small></div>}
export function FitDetails({item}:{item:Item}){const {t}=useLocale();const d=item.details;return <section className="fit-details">{d?.brand&&<p><strong>{t("服裝品牌：")}</strong>{d.brand}</p>}{d&&['height','weight','bust','waist','hips'].some(key=>d[key as keyof ListingDetails]!=null)&&<><h3>{t("試穿者身形參考")}</h3><dl className="measurement-grid">{([['height','身高','cm'],['weight','體重','kg'],['bust','胸圍','cm'],['waist','腰圍','cm'],['hips','臀圍','cm']] as const).map(([key,label,unit])=>d[key]!=null?<div key={key}><dt>{t(String(label))}</dt><dd>{d[key]} {unit}</dd></div>:null)}</dl><small>{t("由出租者選填，非衣服平量尺寸；版型與彈性仍會影響合身程度。")}</small></>}{d?.fitNote&&<p>{t("試穿感受：")}{d.fitNote}</p>}</section>}
export function Gallery({item}:{item:Item}){const {t}=useLocale();const [index,setIndex]=useState(0);const photos=item.photos?.length?item.photos:[item.image];return <div className="gallery"><img className="photo" src={photos[index]??photos[0]} alt={`${item.title} · ${t("照片")} ${index+1}`}/>{photos.length>1&&<><div className="gallery-controls"><button type="button" aria-label={t("上一張照片")} onClick={()=>setIndex((index+photos.length-1)%photos.length)}><ChevronLeft/></button><span aria-live="polite">{index+1} / {photos.length}</span><button type="button" aria-label={t("下一張照片")} onClick={()=>setIndex((index+1)%photos.length)}><ChevronRight/></button></div><div className="gallery-thumbnails">{photos.map((src,i)=><button type="button" key={src+i} aria-label={`${t("查看照片")} ${i+1}`} aria-pressed={index===i} onClick={()=>setIndex(i)}><img src={src} alt=""/></button>)}</div></>}</div>}
export function BookingNextSteps({booking,owner}:{booking:Booking;owner:boolean}){const {t}=useLocale();return <section className="booking-next"><strong>{booking.status==='pending'?t("下一步：等待衣主確認"):booking.status==='accepted'?t("下一步：確認付款與交付安排"):t("這筆申請已結束")}</strong>{booking.status==='pending'?<p>{owner?t("接受前，請確認尺寸、衣況與租期是否合適。"):t("衣主接受前不需付款。你可以在這裡追蹤申請結果。")}</p>:booking.status==='accepted'?<><p>{t("租期已保留。雙方仍需確認押金、運費、寄出日及歸還方式；「已確認」不代表已付款。")}</p>{!owner&&<SocialLinks details={booking.details}/>}<p>{owner?t("請透過雙方約定的聯絡方式確認細節。"):booking.details?.facebook||booking.details?.instagram?t("可由上方社群連結聯絡出租者。"):t("出租者尚未提供社群連結，目前無法由此訂單直接聯絡。")}</p></>:null}<small>{t("平台尚未代收租金或押金，也未串接物流下單；請勿把此頁當作付款或出貨證明。")}</small></section>}
