import type {ListingDetails} from './listing-details';
export type Item={id:string;owner:string;ownerName:string;title:string;series:string;size:string;city:string;price:number;deposit:number;description:string;delivery:string;image:string;created:number;active:number;demo?:boolean;tile?:number;photos?:string[];details?:Partial<ListingDetails>};
export type Booking={id:string;item:string;renter:string;renterName:string;start:string;end:string;status:string;total:number;title:string;owner:string;details?:Partial<ListingDetails>};
export const examples:Item[]=[
 {id:'demo-1',owner:'demo',ownerName:'示範衣櫃',title:'森林吟遊詩人・全套服裝',series:'原創角色',size:'M',city:'台北市',price:350,deposit:1500,description:'青綠色披肩、上衣、短褲與帽飾。此為介面示範，照片由 AI 生成，無法實際租借。',delivery:'面交',image:'/costumes.png',tile:0,created:0,active:1,demo:true},
 {id:'demo-2',owner:'demo',ownerName:'示範衣櫃',title:'星夜魔女・紫色禮裝',series:'原創角色',size:'S',city:'新北市',price:480,deposit:2000,description:'紫色魔女帽、洋裝與配件。此為介面示範，照片由 AI 生成，無法實際租借。',delivery:'宅配',image:'/costumes.png',tile:1,created:0,active:1,demo:true},
 {id:'demo-3',owner:'demo',ownerName:'示範衣櫃',title:'暗紅薔薇・哥德洋裝',series:'原創角色',size:'M',city:'台中市',price:400,deposit:1800,description:'黑紅色多層裙襬洋裝。此為介面示範，照片由 AI 生成，無法實際租借。',delivery:'面交或宅配',image:'/costumes.png',tile:2,created:0,active:1,demo:true},
 {id:'demo-4',owner:'demo',ownerName:'示範衣櫃',title:'海之使者・藍白制服',series:'原創角色',size:'L',city:'高雄市',price:300,deposit:1200,description:'藍白制服與帽飾。此為介面示範，照片由 AI 生成，無法實際租借。',delivery:'面交或宅配',image:'/costumes.png',tile:3,created:0,active:1,demo:true},
 {"id": "demo-5", "owner": "demo", "ownerName": "示範衣櫃", "title": "聖光騎士・白金披風套裝", "series": "奇幻騎士", "size": "L", "city": "台北市", "price": 620, "deposit": 3000, "description": "白金刺繡長袍、披風與輕甲風格配件。 此為介面示範，照片由 AI 生成，無法實際租借。", "delivery": "面交或宅配", "image": "/costumes-fantasy.png", "tile": 0, "created": 0, "active": 1, "demo": true},
 {"id": "demo-6", "owner": "demo", "ownerName": "示範衣櫃", "title": "緋櫻巫女・和風祭典服", "series": "和風角色", "size": "M", "city": "新北市", "price": 380, "deposit": 1600, "description": "白色花紋上衣與緋紅袴裙，附腰帶。 此為介面示範，照片由 AI 生成，無法實際租借。", "delivery": "面交或宅配", "image": "/costumes-fantasy.png", "tile": 1, "created": 0, "active": 1, "demo": true},
 {"id": "demo-7", "owner": "demo", "ownerName": "示範衣櫃", "title": "甜心偶像・粉色舞台裝", "series": "舞台偶像", "size": "S", "city": "台中市", "price": 450, "deposit": 2000, "description": "粉白層次裙、蝴蝶結與舞台風格配件。 此為介面示範，照片由 AI 生成，無法實際租借。", "delivery": "面交或宅配", "image": "/costumes-fantasy.png", "tile": 2, "created": 0, "active": 1, "demo": true},
 {"id": "demo-8", "owner": "demo", "ownerName": "示範衣櫃", "title": "齒輪旅人・蒸汽龐克套裝", "series": "蒸汽龐克", "size": "XL", "city": "高雄市", "price": 550, "deposit": 2500, "description": "棕色長外套、背心、長褲與護目鏡風格配件。 此為介面示範，照片由 AI 生成，無法實際租借。", "delivery": "面交或宅配", "image": "/costumes-fantasy.png", "tile": 3, "created": 0, "active": 1, "demo": true},
 {"id": "demo-9", "owner": "demo", "ownerName": "示範衣櫃", "title": "星辰術師・深藍魔法袍", "series": "魔法學院", "size": "L", "city": "台中市", "price": 520, "deposit": 2200, "description": "深藍星月刺繡長袍與肩披。 此為介面示範，照片由 AI 生成，無法實際租借。", "delivery": "面交或宅配", "image": "/costumes-adventure.png", "tile": 0, "created": 0, "active": 1, "demo": true},
 {"id": "demo-10", "owner": "demo", "ownerName": "示範衣櫃", "title": "霓光行者・未來機能服", "series": "未來都市", "size": "M", "city": "台北市", "price": 460, "deposit": 2000, "description": "黑青色機能外套、內搭與多口袋長褲。 此為介面示範，照片由 AI 生成，無法實際租借。", "delivery": "面交或宅配", "image": "/costumes-adventure.png", "tile": 1, "created": 0, "active": 1, "demo": true},
 {"id": "demo-11", "owner": "demo", "ownerName": "示範衣櫃", "title": "霜葉精靈・銀藍遊俠裝", "series": "精靈冒險", "size": "M", "city": "新北市", "price": 580, "deposit": 2600, "description": "銀藍披風、葉紋刺繡上衣與長褲。 此為介面示範，照片由 AI 生成，無法實際租借。", "delivery": "面交或宅配", "image": "/costumes-adventure.png", "tile": 2, "created": 0, "active": 1, "demo": true},
 {"id": "demo-12", "owner": "demo", "ownerName": "示範衣櫃", "title": "夜幕管家・黑白燕尾服", "series": "哥德角色", "size": "XL", "city": "高雄市", "price": 420, "deposit": 1800, "description": "黑色燕尾服、背心與白色領飾。 此為介面示範，照片由 AI 生成，無法實際租借。", "delivery": "面交或宅配", "image": "/costumes-adventure.png", "tile": 3, "created": 0, "active": 1, "demo": true},
];
