export type LegalKind = 'terms' | 'privacy';
type Bilingual = {zh:string; en:string};
type LegalSection = {id:string; title:Bilingual; paragraphs:Bilingual[]};
type LegalDocument = {title:Bilingual; description:Bilingual; sections:LegalSection[]};
export const LEGAL_UPDATED = '2026-10-10';
export const LEGAL_CONTACT = 'dennis02101014@gmail.com';
export const legalDocuments:Record<LegalKind,LegalDocument> = {
 terms:{
  title:{zh:'服務條款',en:'Terms of Service'},
  description:{zh:'了解 COZ COS CLOSET 的帳號、服裝上架、租借申請、付款交付與使用規範。',en:'Understand accounts, outfit listings, rental requests, payment arrangements and use of COZ COS CLOSET.'},
  sections:[
   {id:'service',title:{zh:'平台與服務範圍',en:'The platform and its services'},paragraphs:[
    {zh:'COZ COS CLOSET（簡稱 COZ COS）由 COZ COS CLOSET 團隊營運，提供 Cosplay 服裝展示、衣櫃分享、上架與租借申請管理。平台協助衣主與租借者整理資訊及申請，不是服裝所有人，也不代替雙方確認服裝適合度或履行個別租借約定。',en:'COZ COS CLOSET (COZ COS) is operated by the COZ COS CLOSET team. It provides cosplay outfit discovery, wardrobe sharing, listings and rental request management. The platform helps owners and renters organize information and requests; it does not own the outfits or confirm their suitability or perform individual rental arrangements on either party’s behalf.'},
    {zh:'目前平台不提供線上收款、代收押金、履約保管或物流商自動建單。示範服裝僅供展示，不開放租借。Facebook 或 Instagram 連結是衣主自行提供的參考資訊，不代表平台已驗證身分或保證交易安全。',en:'The platform currently does not process online payments, hold deposits, provide escrow or create courier orders automatically. Demo outfits are for display and cannot be rented. Facebook and Instagram links are supplied by owners for reference; they do not establish platform-verified identity or a guarantee of transaction safety.'}
   ]},
   {id:'accounts',title:{zh:'帳號與安全',en:'Accounts and security'},paragraphs:[
    {zh:'請使用你有權使用的第三方帳號登入，提供正確資料並妥善保護帳號。不得冒用他人、繞過權限限制或以自動化方式干擾服務。懷疑帳號遭未授權使用時，請聯絡團隊，並透過登入服務商保護原帳號。',en:'Sign in with a third-party account you are authorized to use, provide accurate information and protect your account. Do not impersonate others, bypass access controls or disrupt the service through automation. If you suspect unauthorized use, contact the team and secure your original account with your sign-in provider.'},
    {zh:'使用者應具備作成相關租借約定所需的法律能力；依法需要法定代理人同意或協助時，應先取得同意或協助。登入方式依網站實際啟用狀態提供，標示「準備中」的選項尚不可使用。',en:'Users must have the legal capacity needed for their rental arrangements. Obtain a legal representative’s consent or assistance when required by applicable law. Sign-in options depend on which providers are enabled; options marked as coming soon are not yet available.'}
   ]},
   {id:'listings',title:{zh:'上架資訊、照片與內容權利',en:'Listings, photos and content rights'},paragraphs:[
    {zh:'衣主應有權出租所上架服裝，並如實提供照片、品牌、尺寸、服裝狀況、配件、租金、押金及交付資訊。身高、體重、三圍與社群連結可選填；請只提供有權公開的資料，避免照片或說明包含他人的個資。',en:'Owners must be entitled to rent out their listed outfits and accurately describe photos, brand, sizing, condition, accessories, rental prices, deposits and delivery options. Height, weight, body measurements and social links are optional. Only publish information you are entitled to disclose, and avoid including other people’s personal data in photos or descriptions.'},
    {zh:'你保留自己上傳內容的權利，並允許平台在提供、展示及管理本服務所必要的範圍內儲存、重製與呈現內容。不得上傳侵權、違法、欺詐、騷擾或不相關內容。發現疑似侵權或錯誤資訊時，可透過聯絡信箱提供具體商品資訊。',en:'You retain your rights in uploaded content and allow the platform to store, reproduce and display it as necessary to provide, present and administer this service. Do not upload infringing, unlawful, fraudulent, harassing or unrelated content. Report suspected infringement or inaccurate information by emailing details identifying the listing.'}
   ]},
   {id:'requests',title:{zh:'租借申請與確認',en:'Rental requests and confirmation'},paragraphs:[
    {zh:'租借者應先閱讀商品資訊，與衣主確認尺寸、狀況、配件與日期，再提出申請。送出申請不會扣款，也不代表已付款、已寄出或交易已完成。網站上的確認與申請紀錄不取代雙方對付款及履約細節的約定。',en:'Renters should read listing information and confirm sizing, condition, accessories and dates with the owner before requesting a rental. Submitting a request does not charge you or mean that payment, shipment or the transaction has been completed. Request and acceptance records do not replace the parties’ arrangements about payment and performance.'},
    {zh:'目前租期為從當日起的 1 至 30 天，衣主可接受或拒絕待處理申請；租借者可取消尚待處理的申請。已確認租借如需變更或取消，請直接與衣主協商並保留約定紀錄。實際可用日期以商品狀態、已確認租期與雙方確認結果為準。',en:'Requests currently cover 1 to 30 days starting no earlier than today. Owners may accept or decline pending requests, and renters may cancel pending requests. Discuss changes or cancellation of an accepted rental directly with the owner and keep a record of the agreement. Availability depends on listing status, accepted rental dates and the parties’ confirmation.'}
   ]},
   {id:'payment',title:{zh:'租金、押金與付款',en:'Rental prices, deposits and payment'},paragraphs:[
    {zh:'租金、押金、運費、付款方式及退款或押金返還條件，須由雙方在付款前確認。網站顯示的租金合計供整理申請使用，不包含未另行列明或約定的運費及其他費用，也不是收款或退款憑證。',en:'Both parties must confirm rental charges, deposits, shipping costs, payment methods and refund or deposit-return conditions before payment. The displayed rental total helps organize the request; it does not include shipping or other charges unless separately stated or agreed, and is not proof of payment or refund.'},
    {zh:'平台目前不經手款項，也不提供自動扣款或退款。付款前請核對交易對象與約定，避免向身分不明者付款或提供金融帳號的登入資料。付款及退款爭議應先與交易對方聯絡。',en:'The platform currently does not handle money, charge users automatically or issue refunds. Verify the counterparty and agreed terms before paying, and do not disclose financial-account login credentials. Raise payment or refund disputes with the other party first.'}
   ]},
   {id:'delivery',title:{zh:'交付、使用與歸還',en:'Delivery, use and return'},paragraphs:[
    {zh:'請於租借前約定面交或寄送方式、運費負擔、寄出及歸還日期、包裝、清潔方式與遺失或損壞的處理。平台不保證物流時效；收件地址與聯絡方式請僅提供給需要履約的對方，不要放在公開商品說明。',en:'Before renting, agree on handover or shipping, shipping costs, dispatch and return dates, packaging, cleaning and how loss or damage will be handled. The platform does not guarantee courier delivery times. Share delivery addresses and contact details only with the party who needs them to fulfill the rental, not in public listing descriptions.'},
    {zh:'交付與歸還時建議雙方確認並記錄服裝、配件及狀況。租借者應依約使用及保管，不擅自改造或轉租；遇到尺寸、狀況或配送問題，應儘早聯絡衣主。',en:'At handover and return, both parties should check and record the outfit, accessories and condition. Renters should use and care for outfits as agreed, without unauthorized alterations or subletting. Contact the owner promptly about fit, condition or delivery problems.'}
   ]},
   {id:'disputes',title:{zh:'取消、損壞與爭議處理',en:'Cancellation, damage and disputes'},paragraphs:[
    {zh:'取消、延遲、損壞、遺失、押金扣除及退款方式，以雙方事先約定與適用法律為準；平台不另行設定自動罰款或賠償金額。發生爭議時，請保留商品資訊、溝通、付款及交付紀錄，先與對方協商。',en:'Cancellation, delays, damage, loss, deposit deductions and refunds are governed by the parties’ prior arrangements and applicable law. The platform does not impose automatic penalties or compensation amounts. Keep listing, communication, payment and delivery records and first try to resolve disputes with the other party.'},
    {zh:'可向團隊反映疑似詐騙、違規或平台功能問題；團隊可依可取得資訊協助查核平台紀錄及處理違規內容，但不承諾代為裁定私人交易爭議或保證款項返還。這不限制任何一方依法申訴或尋求救濟的權利。',en:'Report suspected fraud, rule violations or platform problems to the team. The team may review available platform records and address prohibited content, but does not promise to adjudicate private disputes or guarantee recovery of money. This does not limit either party’s right to make a complaint or seek remedies under applicable law.'}
   ]},
   {id:'moderation',title:{zh:'違規處理與服務調整',en:'Moderation and service changes'},paragraphs:[
    {zh:'為保護服務及使用者，團隊可查核檢舉、下架違規商品或限制違規使用，並保留必要管理紀錄。因維護、第三方登入、網路或託管服務異常，部分功能可能暫時無法使用；如需確認既有租借安排，請與交易對方聯繫。',en:'To protect the service and its users, the team may review reports, remove prohibited listings or restrict misuse, and keep necessary administrative records. Maintenance, third-party sign-in, network or hosting problems may temporarily affect features. Contact your counterparty to confirm existing rental arrangements when necessary.'},
    {zh:'條款如有更新，將在本頁調整內容與更新日期；重大服務變更會透過網站可用方式告知。不以本條款排除依法不得限制的使用者權利或平台責任。',en:'Changes to these terms will be reflected on this page with an updated date. Material service changes will be communicated through available website channels. These terms do not exclude user rights or platform responsibilities that cannot lawfully be limited.'}
   ]},
   {id:'contact',title:{zh:'聯絡團隊',en:'Contact the team'},paragraphs:[
    {zh:'服務、上架檢舉、內容權利或租借流程問題，請寄信至下方聯絡信箱，提供相關商品或申請資訊與問題說明。不要傳送密碼、第三方登入驗證碼或完整金融登入資料。個人資料的使用與權利申請，請另參閱隱私權政策。',en:'Email the contact address below about the service, listing reports, content rights or rental procedures. Include the relevant listing or request information and a description of the problem. Do not send passwords, sign-in verification codes or financial-account login details. See the Privacy Policy for personal-data use and rights requests.'}
   ]}
  ]
 },
 privacy:{
  title:{zh:'隱私權政策',en:'Privacy Policy'},
  description:{zh:'了解 COZ COS CLOSET 收集的資料、公開資訊、Cookie、資料保存與個資權利申請方式。',en:'Learn about data collected by COZ COS CLOSET, public information, cookies, retention and personal-data requests.'},
  sections:[
   {id:'operator',title:{zh:'營運者與政策範圍',en:'Operator and policy scope'},paragraphs:[
    {zh:'COZ COS CLOSET 團隊營運 closet.cozcos.com。本政策說明使用網站探索、登入、上架及租借申請時，我們如何處理個人資料。隱私問題與權利申請可寄至下方聯絡信箱。外部社群、登入服務及物流或付款對象另依各自政策處理資料。',en:'The COZ COS CLOSET team operates closet.cozcos.com. This policy describes how we process personal data when you browse, sign in, list outfits or make rental requests. Contact the email address below about privacy or personal-data rights. External social networks, sign-in providers and shipping or payment counterparties process data under their own policies.'}
   ]},
   {id:'collected',title:{zh:'收集哪些資料、用於什麼目的',en:'What we collect and why'},paragraphs:[
    {zh:'登入：從已啟用的第三方登入服務取得帳號識別、姓名、Email，以及該服務提供且本網站使用的頭貼資料，用來建立帳號、顯示帳號資訊、維持登入與辨識操作權限。我們不取得你的 Google、Apple 或 LINE 密碼；準備中的登入選項尚未提供服務。',en:'Sign-in: enabled third-party sign-in providers supply an account identifier, name, email and, where supported and used by this website, profile picture information. We use these to create your account, display account information, maintain sessions and authorize actions. We do not receive your Google, Apple or LINE password. Sign-in options marked as coming soon are not yet active.'},
    {zh:'上架：儲存你提供的衣主顯示名稱、地區、服裝說明、照片、品牌、尺寸、租金、押金與交付方式；身高、體重、胸圍、腰圍、臀圍、適穿說明及社群連結為選填，用於呈現商品與協助租借者判斷。',en:'Listings: we store the owner display name, location, outfit description, photos, brand, size, rental price, deposit and delivery options you provide. Height, weight, bust, waist, hip measurements, fit notes and social links are optional and help describe listings and inform rental decisions.'},
    {zh:'申請與管理：儲存租借者識別及姓名、商品、租期、申請狀態及租金合計，用於租借申請與雙方管理紀錄；管理者操作、下架原因與時間會記錄，以維護平台安全與處理檢舉。你寄給團隊的來信及附件則用於回覆、查核與處理請求。',en:'Requests and administration: we store the renter identifier and name, listing, dates, request status and rental total to manage rental requests and records for both parties. Administrator actions, removal reasons and timestamps are recorded for platform safety and report handling. Emails and attachments sent to the team are used to respond to, review and handle your requests.'}
   ]},
   {id:'visibility',title:{zh:'哪些資料公開、誰能查看',en:'Public information and access'},paragraphs:[
    {zh:'上架的衣主顯示名稱、地區、服裝資料、照片，以及你選填的身形資訊與社群連結會供網站訪客查看；公開頁面或照片可能被搜尋引擎或他人取得。不要把住址、證件、銀行資料或他人的私密資料寫入商品說明或照片。',en:'Visitors can view listed owner display names, locations, outfit information, photos and optional measurements and social links. Search engines or others may obtain public pages or photos. Do not put home addresses, identity documents, banking information or other people’s private data in listing descriptions or photos.'},
    {zh:'帳號 Email 不列在公開商品資料中。租借申請紀錄提供給相關租借者、衣主及有權限的管理者；團隊僅在服務管理、安全、回覆請求及必要義務範圍內使用相關資料。下架會停止正常商品展示，但不代表資料或既有照片立即刪除。',en:'Account email addresses are not included in public listing information. Rental records are available to the relevant renter, owner and authorized administrators. The team uses relevant data for service administration, security, handling requests and necessary obligations. Removing a listing stops its normal display but does not mean its data or existing photos are immediately deleted.'}
   ]},
   {id:'storage',title:{zh:'Cookie 與瀏覽器儲存',en:'Cookies and browser storage'},paragraphs:[
    {zh:'cos_session 為必要登入 Cookie，登入有效期目前最長 7 天；OAuth 流程使用短期狀態 Cookie 與伺服器驗證資料來防止登入請求遭冒用。登出會使目前登入工作階段失效。封鎖必要 Cookie 可能讓登入或帳號功能無法正常運作。',en:'cos_session is a necessary sign-in cookie with a session lifetime currently up to seven days. OAuth flows use short-lived state cookies and server-side verification data to protect sign-in requests against misuse. Signing out invalidates the current session. Blocking necessary cookies may prevent sign-in or account features from working.'},
    {zh:'cos_language 與 cos_theme 儲存語言及深淺色偏好，目前效期為一年，切換偏好時會更新。收藏清單以 cos-closet:favorites 儲存在你目前瀏覽器的 localStorage，不會上傳為帳號收藏，也不會跨裝置同步；你可取消收藏或清除瀏覽器網站資料移除清單。',en:'cos_language and cos_theme store language and appearance preferences for one year and are updated when preferences change. Favorites are stored in your current browser’s localStorage under cos-closet:favorites. They are not uploaded as account favorites or synced across devices. Remove them by unfavoriting outfits or clearing this website’s browser data.'},
    {zh:'目前網站程式未加入廣告追蹤像素或第三方行銷分析工具。清除瀏覽器資料會移除偏好及本機收藏，並可能使你登出；不會因此刪除伺服器上的帳號、上架或租借紀錄。',en:'The current website code does not include advertising pixels or third-party marketing analytics. Clearing browser data removes preferences and local favorites and may sign you out; it does not delete account, listing or rental records held on the server.'}
   ]},
   {id:'providers',title:{zh:'第三方服務與資料處理地區',en:'Third-party services and processing locations'},paragraphs:[
    {zh:'網站由 Railway 託管，帳號、上架、租借與管理資料儲存在伺服器資料庫，服裝照片存於託管儲存空間。託管服務在運作、安全及問題排查中可能處理連線、請求及錯誤相關技術資訊。伺服器、登入服務或支援服務所在地可能在臺灣以外，資料可能因使用這些服務而跨境處理。',en:'Railway hosts the website. Account, listing, rental and administrative data are stored in the server database, and outfit photos are stored in hosted storage. Hosting operations, security and troubleshooting may involve technical connection, request and error information. Servers, sign-in providers or support services may be located outside Taiwan, and using these services may involve cross-border processing.'},
    {zh:'第三方登入會依該服務的授權頁面與政策處理登入資料，頭貼載入也可能向頭貼服務發出請求。開啟衣主的 Facebook、Instagram 或其他外部連結後，該網站會依其政策處理資料。平台目前不處理付款卡號或物流收件地址；雙方另行提供給付款、物流或交易對象的資料由相關對象處理。',en:'Third-party sign-in providers process sign-in data under their authorization screens and policies. Loading a profile picture may also send a request to its hosting service. Facebook, Instagram or other external links are governed by those websites’ policies. The platform currently does not process payment-card numbers or shipping addresses; information separately supplied to payment, shipping or rental counterparties is handled by those recipients.'}
   ]},
   {id:'retention',title:{zh:'保存期間與安全',en:'Retention and security'},paragraphs:[
    {zh:'資料在提供帳號、上架、租借管理、處理爭議、安全維護與履行必要義務所需期間保存。網站目前沒有因下架、登出或停止使用而自動刪除帳號與租借資料的功能；如需刪除或停止使用，請聯絡團隊。需要依法或為處理未結事項保留的資料，將依適用情形處理並回覆原因。',en:'Data is retained as needed to provide accounts, listings and rental management, handle disputes, maintain security and fulfill necessary obligations. The website currently does not automatically delete account or rental data when you remove listings, sign out or stop using it. Contact the team to request deletion or restriction. Where records need to be retained for legal obligations or unresolved matters, we will explain the applicable reason in our response.'},
    {zh:'網站使用 HTTPS、登入工作階段與操作權限控制保護資料；這些措施不能保證所有風險均被排除。請勿向任何人提供密碼、登入驗證碼或私密金融資料，並在共用裝置使用後登出。',en:'The website uses HTTPS, sign-in sessions and authorization controls to protect data. These measures cannot eliminate every risk. Do not share passwords, sign-in verification codes or private financial information, and sign out after using a shared device.'}
   ]},
   {id:'rights',title:{zh:'你的權利與申請方式',en:'Your rights and how to make a request'},paragraphs:[
    {zh:'你可依法請求查詢或閱覽資料、取得複本、補充或更正、停止蒐集處理或利用，以及刪除個人資料。請用與帳號相關的 Email 寄至下方聯絡信箱，說明請求與相關帳號或商品；團隊可能要求合理的身分確認，以避免資料被他人取得或刪除。不要在來信中提供密碼或驗證碼。',en:'Subject to applicable law, you may request access to your data, a copy, supplementation or correction, restriction of collection, processing or use, and deletion. Email the contact address below using an email associated with your account and describe the request and relevant account or listing. The team may ask for reasonable identity verification to prevent unauthorized disclosure or deletion. Do not include passwords or verification codes.'},
    {zh:'申請透過團隊人工處理，網站目前沒有自助刪除帳號功能。若請求涉及既有租借、第三人權益或必要保存義務，團隊會說明可處理範圍及原因。刪除或停止處理必要帳號資料可能使登入、上架或租借管理無法繼續使用。',en:'The team handles requests manually; the website currently has no self-service account deletion feature. Where a request affects existing rentals, other people’s rights or necessary retention obligations, the team will explain what can be done and why. Deleting or restricting necessary account data may prevent continued sign-in, listing or rental management.'}
   ]},
   {id:'choices',title:{zh:'是否提供資料與政策更新',en:'Your choices and policy updates'},paragraphs:[
    {zh:'你可以不登入並瀏覽公開服裝。拒絕提供登入所需識別、姓名或 Email，將無法建立租借帳號；缺少必要商品資訊或照片可能無法上架，缺少租期則無法申請租借。不提供選填身形或社群連結不影響基本上架功能。',en:'You may browse public outfits without signing in. Without the identifiers, name or email needed for sign-in, a rental account cannot be created. Missing required listing information or photos may prevent publication; missing rental dates prevent a request. Omitting optional measurements or social links does not prevent basic listing functionality.'},
    {zh:'如資料使用方式或功能有變更，團隊會更新本頁與更新日期，重大變更透過網站可用方式告知。你也可以隨時透過下方聯絡信箱詢問目前資料處理方式。',en:'If data uses or features change, the team will update this page and its date and communicate material changes through available website channels. You can also ask about current data processing by emailing the contact address below.'}
   ]}
  ]
 }
};
