import assert from 'node:assert/strict';
const origin=new URL(process.argv[2]||'http://127.0.0.1:5184').origin;
const page=async path=>{const r=await fetch(origin+path);assert.equal(r.status,200,path);return r.text()};
const home=await page('/');assert.match(home,/<title>COZ COS CLOSET.*Cosplay/);assert.match(home,/rel="canonical" href="https:\/\/cos-closet-production.up.railway.app\/?"/);assert.match(home,/name="description"/);assert.match(home,/Cosplay 服裝租借/);assert.match(home,/property="og:image"/);
const schema=home.match(/<script type="application\/ld\+json">(.*?)<\/script>/s);assert.ok(schema);const graph=JSON.parse(schema[1]);assert.equal(graph['@context'],'https://schema.org');assert.ok(graph['@graph'].some(n=>n['@type']==='WebSite'&&n.name==='COZ COS CLOSET'));
const robots=await page('/robots.txt');assert.match(robots,/Allow: \//);assert.match(robots,/Sitemap: https:\/\/cos-closet-production.up.railway.app\/sitemap.xml/);assert.doesNotMatch(robots,/Disallow: \/\s*$/m);
const sitemap=await page('/sitemap.xml');assert.equal((sitemap.match(/<loc>/g)||[]).length,2);assert.match(sitemap,/\/explore<\/loc>/);assert.doesNotMatch(sitemap,/\/admin|\/login|\/api\//);
const explore=await page('/explore');assert.match(explore,/<title>探索 Cosplay/);assert.match(explore,/costume-card/);assert.match(explore,/rel="canonical" href="https:\/\/cos-closet-production.up.railway.app\/explore"/);
const login=await page('/login');assert.match(login,/name="robots" content="noindex, nofollow"/);assert.doesNotMatch(login,/rel="canonical"/);
const image=await fetch(origin+'/opengraph-image');assert.equal(image.status,200);assert.match(image.headers.get('content-type'),/image\/png/);const bytes=Buffer.from(await image.arrayBuffer());assert.equal(bytes.readUInt32BE(16),1200);assert.equal(bytes.readUInt32BE(20),630);
console.log('PASS SEO: crawlable homepage, unique canonical/title, structured brand data, SSR catalog, robots, sitemap, private-page noindex and 1200x630 share image.');
